// ======= DO NOT EDIT THIS FILE ============
import java.io.*;
class Main {
   public static void main(String args[]) throws Exception {
       BufferedReader in = new BufferedReader(new InputStreamReader(System.in));
       System.out.print("Enter person name: ");
       String name = in.readLine();
       System.out.print("Enter worker salary: ");
       int salary = Integer.parseInt(in.readLine());
       System.out.print("Enter worker department name: ");
       String deptName = in.readLine();            
       System.out.print("Enter TC: ");
       int tc = Integer.parseInt(in.readLine());
       System.out.println("OUTPUT:");      
       if(tc == 1) {
            Person b = new Person(name);
            System.out.println(b);
            b = new Worker(name, salary, deptName);
            System.out.println(b);
       }
       else if(tc == 2) {
           Worker b = new Worker(name, salary, deptName);
           System.out.println(b.getSalary());
       }
   }
 }
