// ======= DO NOT EDIT THIS FILE ============
import java.io.*;
public class Main {
    
   public static void main(String args[]) throws Exception {
       
       BufferedReader in = new BufferedReader(new InputStreamReader(System.in));
       System.out.print("Enter customer name: ");
       String customerName = in.readLine();
       System.out.print("Enter reservation code: ");
       String code = in.readLine();
       System.out.print("Enter TC: ");
       int tc = Integer.parseInt(in.readLine());
       System.out.println("OUTPUT:");
       ReservationCode s = new ReservationCode(code, customerName);
       if(tc == 1) 
           System.out.println(s);
       else if(tc == 2)
           System.out.println(s.getCode());      
   }
 }
