

 
import java.util.List;
/*
 * DO NOT EDIT THIS FILE
 */
public interface ICourse { 
    /*
        Sort the list of courses "a" ascending by course fee if st = 1
        otherwise sort the list of courses "a" descending by course name
     */
    
    void f1(List<Course> a, int st);
   
    /*
       count and return numbers of courses which are in the list "a" and 
        has fee greater than or equals given fee 
    */
    public int f2(List<Course> a, double fee);
}
