// ======= DO NOT EDIT THIS FILE ============
import java.io.*;
class Main {
   public static void main(String args[]) throws Exception  {
       BufferedReader in = new BufferedReader(new InputStreamReader(System.in));
       System.out.print("Enter flight route: ");
       String route = in.readLine();
       System.out.print("Enter flight fare: ");
       int fare = Integer.parseInt(in.readLine());
       System.out.print("Enter TC: ");
       int tc = Integer.parseInt(in.readLine());
       System.out.println("OUTPUT:");
       Flight s = new Flight(route,fare);
       if(tc == 1) 
           System.out.println(s);
       else if(tc == 2)
           System.out.println(s.getDeparture());      
   }
 }
